apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
    app.kubernetes.io/managed-by: terraform
spec:
  host: loki.apps.openshift-01.hashicorp.local
  port:
    targetPort: http-metrics
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: loki-gateway
    weight: 100
  wildcardPolicy: None
