apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sentry
  namespace: sentry
  annotations:
    haproxy.router.openshift.io/timeout: 600s
spec:
  host: sentry.apps.openshift-01.hashicorp.local
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: sentry-nginx
    weight: 100
  wildcardPolicy: None
